on: [push]
name: Azure ARM - Bicep
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@main

              # Log into Azure
            - uses: azure/login@v1
              name: Azure Login
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

              # Deploy Bicep file
            - name: deploy stg
              uses: azure/arm-deploy@v1
              with:
                  subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
                  resourceGroupName: ${{ secrets.AZURE_RG }}
                  template: ./main.bicep
                  parameters: storagePrefix=stg
                  failOnStdErr: false
